# Generated by Django 4.0.4 on 2022-05-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkLinkedIn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkLusofona',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='competencias',
            field=models.ManyToManyField(blank=True, to='portfolio.competencia'),
        ),
    ]
