# Generated by Django 4.0.4 on 2022-05-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_cadeira_professores_cadeira_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
        ),
    ]
