# Generated by Django 4.0.4 on 2022-05-25 16:00

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_cadeira_nome_alter_pessoa_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to=portfolio.models.resolution_path),
        ),
    ]
