# Generated by Django 4.0.4 on 2022-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('prioridade', models.IntegerField(default=1)),
                ('concluido', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
