# Generated by Django 4.0.4 on 2022-05-29 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_post_delete_comment_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
