# Generated by Django 4.0.4 on 2022-06-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
