# Generated by Django 4.0.4 on 2022-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_noticia_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
    ]
