# Generated by Django 4.0.4 on 2022-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_projeto_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('orientador', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('gitLink', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
