# Generated by Django 4.0.4 on 2022-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('acronimo', models.CharField(max_length=50)),
                ('anoCriado', models.CharField(max_length=50)),
                ('criador', models.CharField(max_length=50)),
                ('logotipo', models.ImageField(null=True, upload_to='media/')),
                ('link', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
