# Generated by Django 4.0.4 on 2022-06-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_tecnologias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnologias',
            new_name='Tecnologia',
        ),
    ]
