# Generated by Django 4.0.4 on 2022-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_rename_tecnologias_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
